version: '3.8'

services:
    database:
        container_name: postgres
        image: postgres
        volumes:
            - database:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: transcendance
            POSTGRES_PASSWORD: strong-password
        networks:
            - nesjs-network
        ports:
            - 5432:5432
    # dev:
    #     container_name: nestjs_api_dev
    #     image: nestjs-api-dev:1.0.0
    #     user: "${UID}:${GID}"
    #     build:
    #         context: .
    #         target: development
    #         dockerfile: ./Dockerfile
    #     command: npm run start:dev
    #     ports:
    #         - 3000:3000
    #         - 9229:9229
    #     networks:
    #         - nesjs-network
    #     volumes:
    #         - .:/usr/src/app
    #         - node_modules:/usr/src/app/node_modules
    #     restart: unless-stopped

networks:
  nesjs-network:
volumes:
  node_modules:
  database: